/// Flutter icons Monday
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Monday
///      fonts:
///       - asset: fonts/Monday.ttf
///
/// 
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
/// * Fontelico, Copyright (C) 2012 by Fontello project
///         Author:    Crowdsourced, for Fontello project
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://fontello.com
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
///
import 'package:flutter/widgets.dart';

class Monday {
  Monday._();

  static const _kFontFam = 'Monday';

  static const IconData menu = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData menu_1 = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData lightbulb = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData temperatire = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData up_hand = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData flash_on = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData power = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData power_settings_new = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData fire = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData attention = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData down_open = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData up_open = IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData fingerprint = IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData keyboard_arrow_right = IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData plus = IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData picture = IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData camera = IconData(0xe810, fontFamily: _kFontFam);
  static const IconData videocam = IconData(0xe811, fontFamily: _kFontFam);
  static const IconData grain = IconData(0xe812, fontFamily: _kFontFam);
  static const IconData ok_circled2 = IconData(0xe813, fontFamily: _kFontFam);
  static const IconData new_releases = IconData(0xe814, fontFamily: _kFontFam);
  static const IconData torso = IconData(0xe815, fontFamily: _kFontFam);
  static const IconData bat_charge = IconData(0xe816, fontFamily: _kFontFam);
  static const IconData bat3 = IconData(0xe817, fontFamily: _kFontFam);
  static const IconData bat2 = IconData(0xe818, fontFamily: _kFontFam);
  static const IconData bat1 = IconData(0xe819, fontFamily: _kFontFam);
  static const IconData device_hub = IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData cog_alt = IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData chart_bar = IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData help = IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData logout = IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData trash = IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData pencil = IconData(0xe820, fontFamily: _kFontFam);
  static const IconData chat = IconData(0xe821, fontFamily: _kFontFam);
  static const IconData droplet = IconData(0xe822, fontFamily: _kFontFam);
  static const IconData cloud_sun = IconData(0xe823, fontFamily: _kFontFam);
  static const IconData clock = IconData(0xe824, fontFamily: _kFontFam);
  static const IconData ok_1 = IconData(0xe825, fontFamily: _kFontFam);
  static const IconData eq = IconData(0xe826, fontFamily: _kFontFam);
  static const IconData spin3 = IconData(0xe832, fontFamily: _kFontFam);
  static const IconData calendar_full = IconData(0xe836, fontFamily: _kFontFam);
  static const IconData bell_alt = IconData(0xf0f3, fontFamily: _kFontFam);
  static const IconData circle_empty = IconData(0xf10c, fontFamily: _kFontFam);
  static const IconData shield = IconData(0xf132, fontFamily: _kFontFam);
  static const IconData toggle_off = IconData(0xf204, fontFamily: _kFontFam);
  static const IconData toggle_on = IconData(0xf205, fontFamily: _kFontFam);
}
